# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    paths:
      - '**.gradle.kts'
      - '**.properties'
      - 'api/**'
      - 'src/**'
      - '.github/workflows/**'
    types: [opened, synchronize, reopened]
permissions:
  contents: read

jobs:
  jvm:
    name: JVM tests on ${{ matrix.os.runner }}
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runner: windows-latest
            command: ./gradlew.bat jvmTest
          - runner: ubuntu-latest
            command: ./gradlew jvmTest
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDKs 8 and 21
      uses: actions/setup-java@v5
      with:
        java-version: |
          8
          21
        distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v6
    - name: Run JVM tests
      run: ${{ matrix.os.command }}

  web:
    name: Web tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDKs 8 and 21
      uses: actions/setup-java@v5
      with:
        java-version: |
          8
          21
        distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v6
    - name: Run web tests
      run: ./gradlew jsBrowserTest wasmJsBrowserTest

  api:
    name: API check
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDKs 8 and 21
      uses: actions/setup-java@v5
      with:
        java-version: |
          8
          21
        distribution: 'zulu'
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v6
    - name: Check API
      run: ./gradlew checkLegacyAbi
